elements:
  Additional Divergence Loss:
    gain_loss: -2.0
    idx: 3
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
  Atmospheric Propagation Loss:
    gain_loss: -2.0
    idx: 5
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
  Atmospheric turbulence losses:
    gain_loss: -15.0
    idx: 6
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
  Free Space Loss:
    gain_loss: -257.0
    idx: 4
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
  Rx Antenna Gain:
    gain_loss: 126.0
    idx: 7
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
  Rx Transmission Loss:
    gain_loss: -3.0
    idx: 8
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
  Tx Antenna Gain:
    gain_loss: 103.0
    idx: 1
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
  Tx Tranmission Loss:
    gain_loss: -3.0
    idx: 2
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
general_values:
  input_power: 30.0
  rx_sys_threshold: -30.0
  total_gain: null
  total_margin: null
settings:
  case_type: nominal
