elements:
  Free Space:
    gain_loss: null
    idx: 3
    input_type: parameter_set_2
    link_type: FREE_SPACE
    parameters:
      angle: 0.0
      distance: 0.0
      gs_altitude: 0.0
      sc_altitude: 0.0
      wavelength: 0.0
  GS RX Ant:
    gain_loss: null
    idx: 1
    input_type: parameter_set_1
    link_type: RX
    parameters:
      antenna_diameter: 0.0
      antenna_efficiency: 0.0
      wavelength: 100.0
  SC TX Ant:
    gain_loss: 10.0
    idx: 2
    input_type: gain_loss
    link_type: TX
    parameters: null
settings:
  case_type: nominal
