elements:
  GS_RX_Ant:
    idx: 0
    gain_loss: 2
    input_type: parameter_set_1
    link_type: RX
    parameters:
      antenna_diameter: val1
      antenna_efficiency: val2
      wavelength: 100
  SC_TX_Ant:
    idx: 1
    gain_loss: 10
    input_type: gain_loss
    link_type: TX
  free_space:
    idx: 2
    gain_loss: -8
    input_type: parameter_set_2
    link_type: FREE_SPACE
    parameters:
      angle: null
      distance: null
      gs_altitude: null
      sc_altitude: null
      wavelength: null
generic_values:
  altitude: 800
settings:
  case_type: nominal
