elements:
  Free Space:
    gain_loss: '-8'
    input_type: gainloss
    link_type: FREE_SPACE
    parameters:
      parameter1: None
      parameter2: None
      parameter3: None
  GS RX Ant:
    gain_loss: '2'
    input_type: gainloss
    link_type: RECEIVER
    parameters:
      parameter1: val1
      parameter2: val2
      parameter3: '100'
  SC TX Ant:
    gain_loss: '10'
    input_type: gainloss
    link_type: TRANSMITTER
    parameters:
      parameter1: None
      parameter2: None
      parameter3: None
generic_values:
  altitude: 800
settings:
  case_type: nominal
