elements:
  Free Space:
    gain_loss: '-8'
    index: 1
    input_type: parameter_set_2
    link_type: FREE_SPACE
    parameters:
      angle: None
      distance: None
      gs_altitude: None
      sc_altitude: None
      wavelength: None
  GS RX Ant:
    gain_loss: '2'
    index: 2
    input_type: parameter_set_1
    link_type: RX
    parameters:
      antenna_diameter: val1
      antenna_efficiency: val2
      wavelength: '100'
  SC TX Ant:
    gain_loss: '10'
    index: 3
    input_type: gain_loss
    link_type: TX
generic_values:
  altitude: 800
settings:
  case_type: nominal
