elements:
  '23':
    gain_loss: 23.0
    idx: 3
    input_type: gain_loss
    link_type: FREE_SPACE
    parameters: null
  SC TX Ant:
    gain_loss: 10.0
    idx: 1
    input_type: gain_loss
    link_type: TX
    parameters: null
  asdff:
    gain_loss: 4.0
    idx: 2
    input_type: gain_loss
    link_type: FREE_SPACE
    parameters: null
settings:
  case_type: nominal
