elements:
  Free Space:
    gain_loss: 2.0
    idx: 4
    input_type: gain_loss
    link_type: FREE_SPACE
    parameters: null
  GS RX Ant:
    gain_loss: null
    idx: 1
    input_type: parameter_set_1
    link_type: RX
    parameters:
      antenna_diameter: 0.0
      antenna_efficiency: 0.0
      wavelength: 100.0
  SC TX Ant:
    gain_loss: 10.0
    idx: 2
    input_type: gain_loss
    link_type: TX
    parameters: null
generic_values:
  altitude: 800
settings:
  case_type: nominal
