elements:
  Free Space:
    gain_loss: -303.2739433373266
    idx: 3.0
    input_type: parameter_set_2
    link_type: FREE_SPACE
    parameters:
      angle: 10.0
      distance: 1500.0
      gs_altitude: 0.0
      sc_altitude: 300.0
      wavelength: 9.999999999999998
  GS RX Ant:
    gain_loss: 148.97389732380213
    idx: 1.0
    input_type: parameter_set_1
    link_type: RX
    parameters:
      antenna_diameter: 1.0
      antenna_efficiency: 0.8
      wavelength: 100.0
  SC TX Ant:
    gain_loss: 10.0
    idx: 2.0
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
general_values:
  input_power: 65.0
  rx_sys_threshold: 6.0
  total_gain: -144.30004601352448
  total_margin: 85.30004601352448
settings:
  case_type: nominal
