elements:
  Free Space:
    Gain [dB]: '-8'
    input_type: gainloss
    link_type: FREE_SPACE
    parameter1: None
    parameter2: None
    parameter3: None
  GS RX Ant:
    Gain [dB]: '2'
    input_type: gainloss
    link_type: RECEIVER
    parameter1: asdfasdfa
    parameter2: asdfasdf
    parameter3: '3213213213213213'
  SC TX Ant:
    Gain [dB]: '10'
    input_type: gainloss
    link_type: TRANSMITTER
    parameter1: None
    parameter2: None
    parameter3: None
generic_values:
  altitude: 800
setting:
  case_type: nominal
