elements:
  FREE_SPACE:
    gain_loss: -8
    input_type: gain_loss
    link_type: FREE_SPACE
    parameters:
      angle: null
      distance1: null
      gs_altitude: null
      sc_altitude: null
      wavelength: null
  'RX_GS    ':
    gain_loss: 2
    input_type: parameters_set_1
    link_type: RX
    parameters:
      antenna_diameter: null
      antenna_efficiency: null
      wavelength: null
  TX_SC:
    gain_loss: 10
    input_type: gain_loss
    link_type: TX
    parameters:
      antenna_diameter: null
      antenna_efficiency: null
      wavelength: null
generic_values:
  altitude: 800
setting:
  case_type: nominal
