elements:
  'RX_GS    ':
    gain_loss: 2
    input_type: gain_loss
    link_type: RX
    parameters:
      parameter1: null
      parameter2: null
      parameter3: null
  TX_SC:
    gain_loss: 10
    input_type: gain_loss
    link_type: TX
    parameters:
      parameter1: null
      parameter2: null
      parameter3: null
  free_space:
    gain_loss: -8
    input_type: gain_loss
    link_type: FREE_SPACE
    parameters:
      parameter1: null
      parameter2: null
      parameter3: null
generic_values:
  altitude: 800
setting:
  case_type: nominal
