elements:
  GS_RX_Ant:
    gain_loss: 2
    input_type: gainloss
    link_type: RECEIVER
    parameters:
      parameter1: null
      parameter2: null
      parameter3: null
  SC_TX_Ant:
    gain_loss: 10
    input_type: gainloss
    link_type: TRANSMITTER
    parameters:
      parameter1: null
      parameter2: null
      parameter3: null
  free_space:
    gain_loss: -8
    input_type: gainloss
    link_type: FREE_SPACE
    parameters:
      parameter1: null
      parameter2: null
      parameter3: null
generic_values:
  altitude: 800
setting:
  case_type: nominal
