elements:
  Atmospheric turbulence:
    gain_loss: -15.0
    idx: 6
    input_type: gain_loss
    link_type: GENERIC
    parameters: null
  Laser:
    gain_loss: 103.0
    idx: 1
    input_type: gain_loss
    link_type: TX
    parameters: null
  Propagation:
    gain_loss: -257.0
    idx: 4
    input_type: gain_loss
    link_type: FREE_SPACE
    parameters: null
  Tx Tranmission Loss:
    gain_loss: -3.0
    idx: 2
    input_type: gain_loss
    link_type: TX
    parameters: null
  antenna:
    gain_loss: 126.0
    idx: 7
    input_type: gain_loss
    link_type: RX
    parameters: null
  atmospheric propagation:
    gain_loss: -2.0
    idx: 5
    input_type: gain_loss
    link_type: FREE_SPACE
    parameters: null
  divergence:
    gain_loss: -2.0
    idx: 3
    input_type: gain_loss
    link_type: TX
    parameters: null
  rx transmission:
    gain_loss: -3.0
    idx: 8
    input_type: gain_loss
    link_type: RX
    parameters: null
general_values:
  input_power: 30.0
  rx_sys_threshold: -30.0
  total_gain: null
  total_margin: null
settings:
  case_type: nominal
