FREE_SPACE:
    parameter_set_1:
        distance:
            description:    distance from spacecraft to ground station
            units:          m
        wavelength:
            description:    radio wavelength in electromagnetic spectrum
            units:          nm
    parameter_set_2:
        angle:
            description:    useful description here
            units:          deg
        distance:
            description:    useful description here
            units:          m
        gs_altitude:
            description:    useful description here
            units:          km
        sc_altitude:
            description:    useful description here
            units:          km
        wavelength:
            description:    useful description here
            units:          nm
RX:
    parameter_set_1:
        antenna_diameter:
            description:    useful description here
            units:          m
        antenna_efficiency:
            description:    useful description here
            units:          m
        wavelength:
            description:    useful description here
            units:          nm
TX:
    parameter_set_1:
        antenna_diameter:
            description:    useful description here
            units:          m
        antenna_efficiency:
            description:    useful description here
            units:          m
        wavelength:
            description:    useful description here
            units:          m
GENERIC:
    gain_loss:
        description:        "Overall gain of the Link Element. \n\tPositive = Gain \n\tNegative = Loss" # Must use double quotes to recognize line-break: \n
        units:              dB
    
LINK_TYPE:
    parameter_set_1:
        parameter_1:
            description:    useful description here
            units:          xx
        parameter_2:
            description:    useful description here
            units:          xx
        parameter_3:
            description:    useful description here
            units:          xx
