FREE_SPACE:
    parameter_set_1:
        distance:
            description:    Distance between spacecraft and ground station
            units:          m
        wavelength:
            description:    Radio signal wavelength
            units:          nm
    parameter_set_2:
        angle:
            description:
            units:          deg
        distance:
            description:    Distance between spacecraft and ground station
            units:          m
        gs_altitude:
            description:    Ground station altitude
            units:          km
        sc_altitude:
            description:    Spacecraft altitude
            units:          km
        wavelength:
            description:    Radio signal wavelength
            units:          nm
RX:
    parameter_set_1:
        antenna_diameter:
            description:
            units:          m
        antenna_efficiency:
            description:
            units:          "-"
        wavelength:
            description:    Radio signal wavelength
            units:          nm
TX:
    parameter_set_1:
        antenna_diameter:
            description:    Diameter of antenna
            units:          m
        antenna_efficiency:
            description:    Efficiency of antenna
            units:          "-"
        wavelength:
            description:    Radio signal wavelength
            units:          nm
GENERIC:
    gain_loss:
        description:        "Overall gain of the Link Element. \n\tPositive = Gain \n\tNegative = Loss" # Must use double quotes to recognize line-break: \n
        units:              dB

#LINK_TYPE:
#    parameter_set_1:
#        parameter_1:
#            description:    useful description here
#            units:          xx
#        parameter_2:
#            description:    useful description here
#            units:          xx
#        parameter_3:
#            description:    useful description here
#            units:          xx
